import { normalizeToy } from '../data/schema.js';
import { findOwnedToy } from './identity-service.js';
import { independentChildrenForParent, linkedChildrenForParent } from './set-service.js';

// Shared Toy Library mutations.  UI cards and future views use the same
// interest/shelf semantics instead of each carrying a local implementation.
export function setToyInterest(store, toyId, value) {
  store.update(state => {
    const toy = state.toys.find(item => item.id === toyId);
    if (toy) toy.interest = toy.interest === value ? null : value;
  }, 'interest');
}

export function toggleToyShelf(store, toyId) {
  store.update(state => {
    const toy = state.toys.find(item => item.id === toyId);
    if (!toy) return;
    toy.status = toy.status === 'active' ? 'stored' : 'active';
    if (toy.status === 'active') toy.lastActivatedAt = new Date().toISOString();
  }, 'shelf');
}

// The one ownership write gate for Standard Catalog and recognition results
// that have been resolved to a Catalog identity.  UI state is deliberately
// not trusted: the guard runs again inside the mutation before writing.
export function createCatalogOwnership(store, source, imageRef, { reason = 'catalog-add' } = {}) {
  const existing = findOwnedToy(source, store.state.toys || []);
  if (existing) return { added:false, toy:existing, reason:'already_owned' };
  const toy = normalizeToy({ ...source, imageRef:imageRef || source.imageRef });
  let result = toy;
  store.update(state => {
    const concurrent = findOwnedToy(source, state.toys || []);
    if (concurrent) { result = concurrent; return; }
    state.toys.push(toy);
  }, reason);
  return { added:result === toy, toy:result, reason:result === toy ? 'created' : 'already_owned' };
}

// Backwards-compatible public name for existing Standard Catalog callers.
// It delegates to the same formal ownership gate used by recognition.
export function addCatalogToy(store, source, imageRef) {
  return createCatalogOwnership(store, source, imageRef, { reason:'catalog-add' });
}

export function parentDeleteImpact(toys = [], parent) {
  return {
    generated:linkedChildrenForParent(toys, parent),
    independent:independentChildrenForParent(toys, parent)
  };
}

// One state transition for parent/set ownership removal. Catalog structure is
// deliberately not consulted: only child rows proven generated by this exact
// ownership group are cascaded. Independent/detached rows are preserved and
// detached so later catalog hydration cannot recreate an ownership relation.
export function deleteToyOwnership(store, toyId, { parentMode = 'cascade_generated' } = {}) {
  const target = store.state.toys.find(item => item.id === toyId);
  if (!target) return { removed:[], preserved:[], target:null };
  let result = { removed:[], preserved:[], target };
  store.update(state => {
    const toy = state.toys.find(item => item.id === toyId);
    if (!toy) return;
    if (toy.set?.kind !== 'parent') {
      if (toy.set?.kind === 'child') markChildIntentionallyRemoved(state.toys, toy);
      state.toys = state.toys.filter(item => item.id !== toy.id);
      preserveDeletedReferences(state, [toy.id]);
      result = { removed:[toy], preserved:[], target:toy };
      return;
    }
    const impact = parentDeleteImpact(state.toys, toy);
    const cascade = parentMode === 'cascade_generated';
    const removed = cascade ? [toy, ...impact.generated] : [toy];
    const removeIds = new Set(removed.map(item => item.id));
    const preserved = [...impact.generated, ...impact.independent].filter(item => !removeIds.has(item.id));
    for (const child of preserved) detachChildFromParent(child, toy);
    state.toys = state.toys.filter(item => !removeIds.has(item.id));
    archiveRemovedOwnerships(state, removed, 'parent_delete_cascade');
    preserveDeletedReferences(state, [...removeIds]);
    result = { removed, preserved, target:toy, impact };
  }, 'toy-delete-ownership');
  return result;
}

function markChildIntentionallyRemoved(toys, child) {
  const parent = toys.find(item => item.id === child.set.parentId);
  if (!parent?.set || parent.set.kind !== 'parent') return;
  const key = child.canonicalKey;
  parent.set.intentionalRemovedChildKeys = [...new Set([...(parent.set.intentionalRemovedChildKeys || []), key])];
  parent.set.childIds = (parent.set.childIds || []).filter(id => id !== child.id);
}
function detachChildFromParent(child, parent) {
  const source = child.set?.ownershipSource === 'independent' || child.purchaseDate || Object.keys(child.purchaseMetadata || {}).length || child.userMetadata?.independentOwnership === true ? 'independent' : 'detached_from_set';
  child.set = { ...child.set, kind:'none', parentId:null, parentCanonicalKey:null, legacyParentIds:[...(child.set?.legacyParentIds || []), parent.id], setName:'', partIndex:null, childIds:[], rotationMode:'whole', ownershipSource:source, generatedFromParentId:null, ownershipGroupId:null, detachedFromSet:true, detachedFromParentOwnershipId:parent.id, detachedAt:new Date().toISOString() };
}
function archiveRemovedOwnerships(state, toys, reason) {
  state.catalogState ||= {};
  state.catalogState.removedOwnerships ||= {};
  for (const toy of toys) {
    if (state.catalogState.removedOwnerships[toy.id]) continue;
    state.catalogState.removedOwnerships[toy.id] = {
      removedAt:new Date().toISOString(), reason,
      canonicalKey:toy.canonicalKey,
      parentCanonicalKey:toy.set?.parentCanonicalKey || null,
      ownership:{ ...toy.set },
      preservedUserData:{ interest:toy.interest, shelfMode:toy.shelfMode, purchaseDate:toy.purchaseDate, purchaseMetadata:toy.purchaseMetadata, notes:toy.notes, userMetadata:toy.userMetadata, imageRef:toy.imageRef }
    };
  }
}
function preserveDeletedReferences(state, ids) {
  const deleted = new Set(ids);
  for (const round of state.rotationHistory || []) {
    const missing = (round.toyIds || []).filter(id => deleted.has(id));
    if (missing.length) {
      round.toyIds = (round.toyIds || []).filter(id => !deleted.has(id));
      round.historicalMissingToyIds = [...new Set([...(round.historicalMissingToyIds || []), ...missing])];
    }
    if (deleted.has(round.toyId)) {
      round.historicalMissingToyIds = [...new Set([...(round.historicalMissingToyIds || []), round.toyId])];
      delete round.toyId;
    }
  }
}
