import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { normalizeImageRef } from '../src/data/schema.js';
import { ImageRepository, packagedAssetUrl } from '../src/data/image-repository.js';
import { catalogImageAsset } from '../src/data/catalog-image-assets.js';

let checks=0; const equal=(actual,expected,message)=>{assert.equal(actual,expected,message);checks++}; const ok=(value,message)=>{assert.ok(value,message);checks++};
const safe={kind:'packaged',path:'catalog-assets/packaged-image-fixture.svg'};
equal(packagedAssetUrl(safe),'./catalog-assets/packaged-image-fixture.svg','safe packaged ref resolves to a same-origin static path');
equal(packagedAssetUrl({kind:'packaged',path:'../secret.svg'}),null,'traversal path is rejected');
equal(packagedAssetUrl({kind:'packaged',path:'https://example.test/image.svg'}),null,'remote URL is rejected');
equal(packagedAssetUrl({kind:'packaged',path:'catalog-assets/fixture.gif'}),null,'unsupported extension is rejected');
equal(packagedAssetUrl({kind:'packaged',path:'catalog-assets/fixture.jpeg'}),'./catalog-assets/fixture.jpeg','JPEG packaged refs resolve to a same-origin static path');
assert.deepEqual(normalizeImageRef({imageRef:safe}),safe);checks++;
equal(normalizeImageRef({imageRef:{kind:'packaged',path:'catalog-assets/../unsafe.svg'}}).kind,'placeholder','schema rejects unsafe packaged refs');
const images=new ImageRepository();
equal(await images.resolve(safe),'./catalog-assets/packaged-image-fixture.svg','resolver does not require IndexedDB for packaged asset');
await access(new URL('../catalog-assets/packaged-image-fixture.svg',import.meta.url)); checks++;
ok((await readFile(new URL('../catalog-assets/packaged-image-fixture.svg',import.meta.url),'utf8')).includes('Toy Rotation'),'fixture is an owned neutral asset, not a brand product image');
const exact=catalogImageAsset('cherrypick-original-magic-playwall');
equal(exact.kind,'packaged','exact product asset is packaged, not a volatile remote URL');
equal(exact.mimeType,'image/jpeg','exact product asset records the verified MIME');
const exactBytes=await readFile(new URL('../catalog-assets/cherrypick-original-magic-playwall.jpg',import.meta.url));
equal(`sha256:${createHash('sha256').update(exactBytes).digest('hex')}`,exact.contentHash,'exact product asset hash is stable');
equal(await images.resolve(exact),'./catalog-assets/cherrypick-original-magic-playwall.jpg','real packaged asset resolves lazily without IndexedDB');
const manifest=JSON.parse(await readFile(new URL('../runtime-js-manifest.json',import.meta.url),'utf8'));
ok(manifest.files.some(file=>file.path==='catalog-assets/cherrypick-original-magic-playwall.jpg'),'real packaged asset is included in the runtime manifest');
console.log(`catalog packaged image foundation v0.11.6: PASS (${checks} assertions)`);
