import assert from 'node:assert/strict';
import { CatalogRepository } from '../src/domain/catalog-repository.js';
import { buildCatalogCountDiagnostic } from '../src/features/catalog-count-diagnostic.js';

let checks=0; const equal=(actual,expected,message)=>{assert.equal(actual,expected,message);checks++}; const ok=(value,message)=>{assert.ok(value,message);checks++};
const state={catalogState:{tombstones:{'hidden-row':{deletedAt:'now'}},adminEdits:{'public-row':{aliases:['Public']}},imageRefsByKey:{},imageRefsByIdentity:{},learnedEntries:[{id:'local-row',canonicalKey:'local-row',brand:'L',productName:'Local',reviewStatus:'approved'}],remoteEntries:[{id:'local-remote',canonicalKey:'local-remote',brand:'R',productName:'Remote local',reviewStatus:'approved'}]}};
const store={state,update(fn){fn(state);}};
const catalog=new CatalogRepository(store);
catalog.applyBase([{id:'public-row',canonicalKey:'public-row',brand:'A',productName:'Public',reviewStatus:'approved'},{id:'review-row',canonicalKey:'hape-shape-sorter',brand:'A',productName:'Review hold',reviewStatus:'approved'},{id:'hidden-row',canonicalKey:'hidden-row',brand:'A',productName:'Hidden',reviewStatus:'approved'}]);
catalog.applyRemote([{id:'public-row',canonicalKey:'public-row',brand:'A',productName:'Public remote',reviewStatus:'approved'}]);
equal(catalog.active.length,4,'active count applies tombstones and canonical consolidation');
equal(catalog.getPublicVisibleCatalogCount(),3,'public count excludes review-only rows independently of search');
const exported=buildCatalogCountDiagnostic({catalog,build:{RELEASE:'test',buildId:'build-1'},uiSearchRows:3,exportedAt:'2026-09-15T00:00:00.000Z'});
equal(exported.readOnly,true,'count diagnostic is read-only');
equal(exported.catalog.raw.base,3,'diagnostic includes base source count');
equal(exported.catalog.raw.remote,1,'diagnostic includes remote source count');
equal(exported.catalog.raw.localLearned,1,'diagnostic includes local learned source count');
equal(exported.catalog.localAdditions,2,'diagnostic summarizes all local additions');
equal(exported.catalog.adminEdits,1,'diagnostic includes admin edit count without edit contents');
equal(exported.catalog.tombstoneCount,1,'diagnostic includes tombstone count');
equal(exported.catalog.mergedRaw,6,'diagnostic includes merged raw source count');
equal(exported.catalog.canonicalDeduped,5,'diagnostic includes canonical deduplicated count');
equal(exported.catalog.active,4,'diagnostic includes deduplicated active count');
equal(exported.catalog.publicVisible,3,'diagnostic includes public visible count');
equal(exported.ui.searchRows,3,'diagnostic keeps UI search rows separate');
equal(exported.ui.total,3,'diagnostic includes the public-visible UI total');
ok(exported.catalog.remoteIds.includes('public-row'),'diagnostic includes remote identifiers');
ok(exported.catalog.localOnlyIds.includes('local-row'),'diagnostic includes local-only identifiers');
equal(exported.catalog.collisionSummary.total,1,'diagnostic summarizes source canonical collisions');
console.log(`catalog visible count diagnostic v0.11.6: PASS (${checks} assertions)`);
