import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { webcrypto } from 'node:crypto';
const dom=new JSDOM('',{url:'https://reports.test'});
for(const key of ['window','document','localStorage','navigator'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
Object.defineProperty(globalThis,'crypto',{value:webcrypto,configurable:true});
const { AppStore }=await import('../src/data/store.js');
const { SharedCatalogGovernance }=await import('../src/features/shared-catalog-governance.js');
const { getCatalogReports,getPendingCatalogReports,getCatalogReportById,startCatalogReportReview,resolveCatalogReport,dismissCatalogReport }=await import('../src/features/catalog-report-store.js');
const base=()=>({schemaVersion:12,settings:{},profile:{},toys:[{id:'toy'}],wishlist:[{id:'wish'}],drafts:[],rotationHistory:[{toyIds:['toy']}],catalogState:{syncMetadata:{}}});
let assertions=0; const ok=(value,message)=>{assert.ok(value,message);assertions++}; const equal=(actual,expected,message)=>{assert.equal(actual,expected,message);assertions++};
let saved; const store=new AppStore(base(),undefined,{safeSave:state=>{saved=structuredClone(state)}});
let localProviderCalls=0;globalThis.fetch=async()=>{localProviderCalls++;throw new Error('provider must not be called');};
const governance=new SharedCatalogGovernance({store,catalog:{},baseUrl:''});
const first=await governance.submitReport({reportId:'report-1',canonicalKey:'VTech / Count & Learn',reportType:'name_wrong',description:'Name is outdated',attachmentRef:{kind:'personal',id:'personal:report-photo'},appVersion:'test'});
equal(first.id,'report-1','local report id'); equal(getCatalogReports(store.state).length,1,'local source of truth'); equal(getPendingCatalogReports(store.state).length,1,'pending selector');
equal(first.attachmentRef.id,'personal:report-photo','attachment reference retained'); ok(!JSON.stringify(store.state).includes('data:image/'),'no raw attachment canonical');
equal(store.state.catalogState.syncMetadata.governanceOutbox.length,1,'sync intent committed atomically'); equal(store.state.catalogState.syncMetadata.governanceOutbox[0].payload.attachmentTransport,'deferred_until_remote_contract_updated','no raw remote transport');
equal(localProviderCalls,0,'local report persistence makes zero AI/provider calls');
const reopened=new AppStore(saved); equal(getCatalogReportById(reopened.state,'report-1').note,'Name is outdated','reload persistence');
const ownershipBefore=JSON.stringify({toys:store.state.toys,wishlist:store.state.wishlist,history:store.state.rotationHistory});
store.update(state=>startCatalogReportReview(state,'report-1'),'report-review'); equal(getCatalogReportById(store.state,'report-1').status,'reviewing','review lifecycle'); equal(getPendingCatalogReports(store.state).length,1,'reviewing remains pending');
store.update(state=>resolveCatalogReport(state,'report-1',{reason:'fixed'}),'report-resolve'); equal(getCatalogReportById(store.state,'report-1').status,'resolved','resolve lifecycle'); equal(getPendingCatalogReports(store.state).length,0,'resolved leaves pending');
await governance.submitReport({reportId:'report-2',canonicalKey:'vtech-count-learn',reportType:'duplicate',description:'Different report same item'}); equal(getCatalogReports(store.state).length,2,'multiple reports same item');
store.update(state=>{startCatalogReportReview(state,'report-2');dismissCatalogReport(state,'report-2',{reason:'not duplicate'});},'report-dismiss'); equal(getCatalogReportById(store.state,'report-2').status,'dismissed','dismiss lifecycle'); equal(getPendingCatalogReports(store.state).length,0,'dismissed leaves pending');
equal(JSON.stringify({toys:store.state.toys,wishlist:store.state.wishlist,history:store.state.rotationHistory}),ownershipBefore,'report does not mutate ownership');
let safeCalls=0;const failing=new AppStore(base(),undefined,{safeSave:()=>{safeCalls++;const error=new Error('The quota has been exceeded.');error.name='QuotaExceededError';error.code=22;throw error;}});const failingGovernance=new SharedCatalogGovernance({store:failing,catalog:{},baseUrl:''});await assert.rejects(()=>failingGovernance.submitReport({reportId:'fails',canonicalKey:'x',reportType:'other'}),/quota/i);assertions++; equal(safeCalls,1,'safe save attempted once'); equal(getCatalogReports(failing.state).length,0,'safe-save failure is not false success');
let fetchCalls=0;globalThis.fetch=async()=>{fetchCalls++;throw new Error('network unavailable');};const remoteStore=new AppStore(base(),undefined,{safeSave:()=>{}});const remoteGovernance=new SharedCatalogGovernance({store:remoteStore,catalog:{},baseUrl:'https://blocked.example'});await remoteGovernance.submitReport({reportId:'remote-failure',canonicalKey:'x',reportType:'other'});await new Promise(resolve=>setTimeout(resolve,0));equal(getCatalogReportById(remoteStore.state,'remote-failure').status,'pending','remote failure leaves local report pending');ok(fetchCalls>=1,'remote attempt is independent background work');
console.log(`catalog report persistence: PASS (${assertions} assertions)`);
