import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { webcrypto } from 'node:crypto';
const dom=new JSDOM('',{url:'https://report-quota.test'});for(const key of ['window','document','localStorage','navigator'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});Object.defineProperty(globalThis,'crypto',{value:webcrypto,configurable:true});localStorage.clear();
const { AppStore }=await import('../src/data/store.js');const { createCatalogReport,enqueueCatalogReportSyncIntent,getCatalogReports }=await import('../src/features/catalog-report-store.js');
const initial={schemaVersion:12,settings:{},profile:{},toys:[{id:'ownership-sentinel'}],wishlist:[],drafts:[],catalogState:{syncMetadata:{}}};const store=new AppStore(initial);let assertions=0;const ok=(value,message)=>{assert.ok(value,message);assertions++};const equal=(a,b,m)=>{assert.equal(a,b,m);assertions++};
const ref={kind:'personal',id:'personal:single-report-image'};for(let index=0;index<3;index++)store.update(state=>{const report=createCatalogReport(state,{id:`report-${index}`,canonicalKey:'same-item',reportType:'image_wrong',description:`report ${index}`,attachmentRef:ref});enqueueCatalogReportSyncIntent(state,report);},`report-${index}`);
const canonical=JSON.stringify(store.state);equal(getCatalogReports(store.state).length,3,'three reports persisted');ok(!canonical.includes('data:image/'),'canonical has no data URL');ok(!canonical.includes(';base64,'),'canonical has no base64 payload');ok(canonical.includes('attachmentRef'),'attachment reference retained');equal((canonical.match(/personal:single-report-image/g)||[]).length,6,'references only, no duplicated image bytes');ok(canonical.length<5000,'canonical size sanity');for(const job of store.state.catalogState.syncMetadata.governanceOutbox){ok(!('optionalAttachment' in job.payload),'outbox omits raw attachment');equal(job.payload.attachmentTransport,'deferred_until_remote_contract_updated','remote attachment deferred safely');}
const persisted=[...Array(localStorage.length)].map((_,index)=>localStorage.getItem(localStorage.key(index))||'');ok(persisted.some(value=>value.includes('catalogReports')),'canonical was safely persisted');for(const value of persisted){ok(!value.includes('data:image/'),'canonical/shadow/snapshot contain no raw report image');ok(!value.includes(';base64,'),'canonical/shadow/snapshot contain no base64 report image');}
console.log(`catalog report storage quota: PASS (${assertions} assertions)`);
