import assert from 'node:assert/strict';
import { emptyState } from '../src/data/schema.js';
import { runMigrations } from '../src/data/store.js';
import { recordDevelopmentFeedback, updateDevelopmentProfile } from '../src/domain/development-fit.js';

let checks=0; const ok=(value,message)=>{assert.ok(value,message);checks++}; const equal=(actual,expected,message)=>{assert.equal(actual,expected,message);checks++};
const toy={id:'shape-3',canonicalKey:'shape-3',playMechanics:['shape_sorting'],progressionLevel:3,challengeLevel:3};
const state=emptyState();
recordDevelopmentFeedback(state,toy,{difficultyFeedback:'too_easy',rotationCycleId:'r1',now:'2026-01-01'});
equal(state.profile.developmentProfile.shape_sorting.currentLevel,1,'one Too Easy is not a mastery jump');
recordDevelopmentFeedback(state,toy,{difficultyFeedback:'too_easy',rotationCycleId:'r2',now:'2026-01-02'});
equal(state.profile.developmentProfile.shape_sorting.currentLevel,4,'repeated Too Easy advances conservatively beyond the observed level');
ok(state.profile.developmentProfile.shape_sorting.confidence > .5,'repeated evidence increases confidence');
equal(state.profile.developmentProfile.shape_sorting.evidenceCount,2,'evidence count is retained');
recordDevelopmentFeedback(state,toy,{difficultyFeedback:'too_hard',rotationCycleId:'r3',now:'2026-01-03'});
equal(state.profile.developmentProfile.shape_sorting.currentLevel,4,'Too Hard does not erase established mastery');
ok(state.profile.developmentProfile.shape_sorting.confidence < 1,'Too Hard reduces confidence');
recordDevelopmentFeedback(state,toy,{difficultyFeedback:'good_challenge',rotationCycleId:'r4',now:'2026-01-04'});
ok(state.profile.developmentProfile.shape_sorting.confidence > .5,'Good Challenge is positive evidence');
const beforeInterest=structuredClone(state.profile.developmentProfile);
recordDevelopmentFeedback(state,toy,{interestFeedback:'not_interested',rotationCycleId:'r5',now:'2026-01-05'});
equal(state.profile.developmentProfile.shape_sorting.currentLevel,beforeInterest.shape_sorting.currentLevel,'Not Interested does not alter mastery level');
recordDevelopmentFeedback(state,toy,{difficultyFeedback:'just_right',rotationCycleId:'r4',now:'2026-01-06'});
equal(state.developmentFeedbackHistory.filter(item=>item.id==='shape-3:r4').length,1,'feedback in a cycle is editable by replacement');
const reloaded=JSON.parse(JSON.stringify(state));
equal(reloaded.profile.developmentProfile.shape_sorting.currentLevel,state.profile.developmentProfile.shape_sorting.currentLevel,'profile persists through reload serialization');
equal(runMigrations(reloaded).developmentFeedbackHistory.length,state.developmentFeedbackHistory.length,'schema 12 persistence retains feedback history');
equal(Object.keys(updateDevelopmentProfile([])).length,0,'legacy user with no profile remains valid');
console.log(`child mastery profile v0.11.6: PASS (${checks} assertions)`);
