import assert from 'node:assert/strict';
import { emptyState } from '../src/data/schema.js';
import { recordDevelopmentFeedback } from '../src/domain/development-fit.js';

let checks=0; const equal=(actual,expected,message)=>{assert.equal(actual,expected,message);checks++}; const ok=(value,message)=>{assert.ok(value,message);checks++};
const state=emptyState(); const toy={id:'toy-1',canonicalKey:'toy-1',playMechanics:['shape_sorting'],progressionLevel:2,challengeLevel:2};
recordDevelopmentFeedback(state,toy,{difficultyFeedback:'too_easy',rotationCycleId:'cycle-1'});
equal(state.developmentFeedbackHistory[0].difficultyFeedback,'too_easy','difficulty feedback is delegated to the domain record');
equal(state.developmentFeedbackHistory[0].toyId,'toy-1','feedback records the toy identity');
equal(state.developmentFeedbackHistory[0].canonicalKey,'toy-1','feedback records canonical identity');
equal(state.developmentFeedbackHistory[0].mechanisms.join(','),'shape_sorting','feedback records mechanisms through the domain fallback');
equal(state.developmentFeedbackHistory[0].progressionLevel,2,'feedback records progression level');
equal(state.developmentFeedbackHistory[0].challengeLevel,2,'feedback records challenge level');
recordDevelopmentFeedback(state,toy,{difficultyFeedback:'just_right',rotationCycleId:'cycle-2'});
equal(state.developmentFeedbackHistory.find(item=>item.id==='toy-1:cycle-2').difficultyFeedback,'just_right','Just Right stays separate difficulty evidence');
recordDevelopmentFeedback(state,toy,{difficultyFeedback:'good_challenge',rotationCycleId:'cycle-3'});
equal(state.developmentFeedbackHistory.find(item=>item.id==='toy-1:cycle-3').difficultyFeedback,'good_challenge','Good Challenge stays separate difficulty evidence');
recordDevelopmentFeedback(state,toy,{difficultyFeedback:'too_hard',rotationCycleId:'cycle-4'});
equal(state.developmentFeedbackHistory.find(item=>item.id==='toy-1:cycle-4').difficultyFeedback,'too_hard','Too Hard stays separate difficulty evidence');
recordDevelopmentFeedback(state,toy,{interestFeedback:'not_interested',rotationCycleId:'cycle-1'});
equal(state.developmentFeedbackHistory.length,4,'same toy and rotation cycle replaces feedback without losing other cycles');
equal(state.developmentFeedbackHistory.find(item=>item.id==='toy-1:cycle-1').interestFeedback,'not_interested','Not Interested is stored as interest feedback');
equal(state.developmentFeedbackHistory.find(item=>item.id==='toy-1:cycle-1').difficultyFeedback,null,'Not Interested does not fabricate difficulty evidence');
equal(JSON.parse(JSON.stringify(state)).developmentFeedbackHistory.length,4,'feedback survives reload serialization');
const main=await import('node:fs/promises').then(fs=>fs.readFile(new URL('../src/main.js',import.meta.url),'utf8'));
ok(main.includes("recordDevelopmentFeedback(state, toy"),'Current Shelf UI calls the Phase A domain writer');
ok(main.includes("['too_easy','difficultyFeedback'], ['just_right','difficultyFeedback'], ['good_challenge','difficultyFeedback'], ['too_hard','difficultyFeedback'], ['not_interested','interestFeedback']"),'the compact selector exposes all five mapped choices');
ok(main.includes('role="alert" aria-live="assertive"'),'feedback persistence errors are immediately announced');
ok(main.includes("shelf.rotation.find(item => item.id === id)"),'feedback is restricted to current rotation toys');
ok(main.includes("if (reason !== 'development-feedback') render();") && main.includes('refreshDevelopmentFeedbackCard(id);'),'successful feedback updates its card without regenerating or redrawing the page');
ok(!main.slice(main.indexOf('function openDevelopmentFeedback'),main.indexOf('function togglePauseToy')).includes('generateNewRotation'),'feedback never regenerates rotation');
ok(!main.slice(main.indexOf('function openDevelopmentFeedback'),main.indexOf('function togglePauseToy')).includes('getRecognition'),'feedback remains zero AI');
console.log(`current shelf development feedback v0.11.6: PASS (${checks} assertions)`);
