import assert from 'node:assert/strict';
import { selectRotation, persistRotationSelection, currentShelfCollections, setCustomPermanent, setManualShelfState } from '../src/domain/rotation-engine.js';
import { challengeLevel, developmentMechanics } from '../src/domain/development-fit.js';

let checks=0; const ok=(value,message)=>{assert.ok(value,message);checks++}; const equal=(actual,expected,message)=>{assert.equal(actual,expected,message);checks++};
const toy=(id,progressionLevel,{minAgeMonths=12,mechanic='shape_sorting',brand=id}={})=>({id,canonicalKey:id,productName:id,brand,minAgeMonths,maxAgeMonths:48,playMechanics:[mechanic],progressionLevel,challengeLevel:progressionLevel,skillCodes:[],categoryCode:'cognitive',set:{kind:'none'}});
const easy=toy('easy',1), right=toy('right',3), challenge=toy('challenge',4), hard=toy('hard',5), unsafe={...toy('unsafe',3,{minAgeMonths:48}),userMetadata:{safety:{minAgeMonths:48}}};
const legacyPuzzle={productName:'Simple Puzzle',categoryCode:'puzzles_matching',minAgeMonths:12};
const olderLegacyPuzzle={...legacyPuzzle,minAgeMonths:48};
ok(developmentMechanics(legacyPuzzle).includes('puzzle'),'legacy Catalog fallback infers a mechanism from metadata');
equal(challengeLevel(legacyPuzzle),challengeLevel(olderLegacyPuzzle),'fallback difficulty does not equate recommended age with challenge');
const pool=[easy,right,challenge,hard,unsafe];
const average=selectRotation({toys:pool,childAgeMonths:24,size:3,childDevelopmentProfile:{shape_sorting:{currentLevel:3}},now:Date.UTC(2026,0,1)});
ok(average.selected.some(item=>item.id==='right'),'same age selects a fitting difficulty');
ok(!average.selected.some(item=>item.id==='unsafe'),'age safety remains a hard boundary');
const advanced=selectRotation({toys:pool,childAgeMonths:24,size:2,childDevelopmentProfile:{shape_sorting:{currentLevel:4}},now:Date.UTC(2026,0,1)});
ok(advanced.selected.some(item=>item.id==='challenge'||item.id==='hard'),'advanced child prefers higher progression');
const tooEasyHistory=[{mechanisms:['shape_sorting'],progressionLevel:3,difficultyFeedback:'too_easy'}];
const easyResult=selectRotation({toys:[right,challenge],childAgeMonths:24,size:1,childDevelopmentProfile:{shape_sorting:{currentLevel:3}},developmentFeedbackHistory:tooEasyHistory,now:Date.UTC(2026,0,1)});
equal(easyResult.selected[0].id,'challenge','Too Easy lowers mastered level and raises next progression opportunity');
const hardHistory=[{mechanisms:['shape_sorting'],progressionLevel:4,difficultyFeedback:'too_hard'}];
const hardResult=selectRotation({toys:[challenge,right],childAgeMonths:24,size:1,childDevelopmentProfile:{shape_sorting:{currentLevel:3}},developmentFeedbackHistory:hardHistory,now:Date.UTC(2026,0,1)});
equal(hardResult.selected[0].id,'right','Too Hard lowers the current recommendation');
ok(hardResult.diagnostics.eligibleRotationCount===2,'Too Hard never permanently excludes a toy');
const challengeHistory=[{mechanisms:['shape_sorting'],progressionLevel:3,difficultyFeedback:'good_challenge'}];
const challengeResult=selectRotation({toys:[right,challenge],childAgeMonths:24,size:1,childDevelopmentProfile:{shape_sorting:{currentLevel:3}},developmentFeedbackHistory:challengeHistory,now:Date.UTC(2026,0,1)});
equal(challengeResult.selected[0].id,'challenge','Good Challenge boosts nearby progression');
const stable=selectRotation({toys:[right,easy],childAgeMonths:24,size:1,childDevelopmentProfile:{shape_sorting:{currentLevel:3}},now:Date.UTC(2026,0,1)});
equal(stable.selected[0].id,'right','Just Right remains stable');
const noInterest=selectRotation({toys:[right,challenge],childAgeMonths:24,size:1,childDevelopmentProfile:{shape_sorting:{currentLevel:3}},developmentFeedbackHistory:[{mechanisms:['shape_sorting'],progressionLevel:3,interestFeedback:'not_interested'}],now:Date.UTC(2026,0,1)});
equal(noInterest.selected[0].id,'right','Not Interested does not lower mastery or distort difficulty fit');
const cold=selectRotation({toys:[easy,right,challenge],childAgeMonths:24,size:2,now:Date.UTC(2026,0,1)});
equal(cold.selected.length,2,'no-feedback cold start remains deterministic and fills target');
const diverse=selectRotation({toys:[...pool.filter(item=>item.id!=='unsafe'),toy('other',3,{mechanic:'matching_sorting',brand:'other'})],childAgeMonths:24,size:3,childDevelopmentProfile:{shape_sorting:{currentLevel:3},matching_sorting:{currentLevel:3}},history:[{toyIds:['right'],mechanisms:['shape_sorting']}],now:Date.UTC(2026,0,1)});
ok(diverse.selected.some(item=>item.playMechanics.includes('matching_sorting')),'diversity and recency remain active');
const state={settings:{rotationSize:2},profile:{developmentProfile:{shape_sorting:{currentLevel:3}}},developmentFeedbackHistory:[],toys:[right,challenge,easy],rotationHistory:[]};
const planned=selectRotation({toys:state.toys,childAgeMonths:24,size:2,childDevelopmentProfile:state.profile.developmentProfile});
persistRotationSelection(state,{selected:planned.selected,diagnostics:planned.diagnostics});
setCustomPermanent(state,right.id,true,{childAgeMonths:24});
equal(currentShelfCollections(state).rotation.length,2,'customPermanent remains outside rotation target');
const offShelf=state.toys.find(item=>!currentShelfCollections(state).rotationIds.includes(item.id)&&item.id!==right.id) || right;
setManualShelfState(state,offShelf.id,'on_shelf',{childAgeMonths:24});
ok(currentShelfCollections(state).manualIds.includes(offShelf.id)||offShelf.id===right.id,'manual shelf contract remains authoritative');
console.log(`rotation development fit v0.11.6: PASS (${checks} assertions)`);
