import assert from 'node:assert/strict';
import { currentShelfCollections, persistRotationSelection, selectRotation, setCustomPermanent, setManualShelfState } from '../src/domain/rotation-engine.js';

let assertions=0; const ok=(value,message)=>{assertions++;assert.ok(value,message)}; const equal=(a,b,message)=>{assertions++;assert.equal(a,b,message)};
const toy=(id,brand='Other',group=null)=>({id,canonicalKey:id,productName:id,brand,minAgeMonths:0,maxAgeMonths:120,categoryCode:'cognitive',skillCodes:[],playMechanics:['matching_sorting'],set:group?{kind:'child',ownershipGroupId:group}:{kind:'none'}});
const pool=[...Array.from({length:8},(_,i)=>toy(`love-${i}`,'Lovevery','love-group')),...Array.from({length:8},(_,i)=>toy(`other-${i}`,'Brand '+i))];
for(const target of [5,7,10]){let history=[];for(let round=0;round<10;round++){const result=selectRotation({toys:pool,history,childAgeMonths:24,size:target,now:Date.UTC(2026,0,round+1)});equal(result.selected.length,target,`target ${target} fills round ${round}`);equal(new Set(result.selected.map(x=>x.id)).size,target,'no duplicates');ok(result.diagnostics.selectedCandidateScores.every(row=>Number.isFinite(row.finalScore)),'score diagnostics');history=[{toyIds:result.selected.map(x=>x.id),mechanisms:result.selected.flatMap(x=>x.playMechanics)},...history].slice(0,3)}}
const state={settings:{rotationSize:5},toys:pool.slice(0,7),rotationHistory:[]}; const first=selectRotation({toys:state.toys,childAgeMonths:24,size:5});persistRotationSelection(state,{selected:first.selected,diagnostics:first.diagnostics});
const offShelf=state.toys.find(x=>!state.rotationHistory[0].toyIds.includes(x.id));setManualShelfState(state,offShelf.id,'on_shelf',{childAgeMonths:24});ok(currentShelfCollections(state).manualIds.includes(offShelf.id),'manual shelf is authoritative');equal(currentShelfCollections(state).rotation.length,4,'manual ordinary toy consumes one target position');setManualShelfState(state,offShelf.id,'stored',{childAgeMonths:24});ok(!currentShelfCollections(state).manualIds.includes(offShelf.id),'manual store removes shelf only');setCustomPermanent(state,state.toys[0].id,true,{childAgeMonths:24});equal(currentShelfCollections(state).permanent.length,1,'custom permanent separate');equal(currentShelfCollections(state).rotation.length,5,'permanent does not consume target');console.log(`rotation v0.11.4: PASS (${assertions} assertions)`);
