const DICTIONARY = {
  en: {
    home:'Home', library:'Toy Library', rotation:'Rotation', wishlist:'Wishlist', settings:'Settings', standardCatalog:'Standard Toy Library',
    addToy:'Add toy', recognizeToy:'Recognize from image', pendingReview:'Pending review', confirmAdd:'Confirm & add', retryRecognition:'Retry recognition', remove:'Remove', edit:'Edit', delete:'Delete', save:'Save', cancel:'Cancel', close:'Close', search:'Search brand / product',
    name:'Name', skills:'Skills', minimumAge:'Minimum age (months)', maximumAge:'Maximum age (months)', image:'Image', language:'Language', theme:'Appearance', system:'Follow system', light:'Light', dark:'Dark', languageEnglish:'English', languageChinese:'Chinese', monthUnit:'mo', removeToy:'Remove from Toy Library', confirmRemoveToy:'Remove this toy from your library?',
    recognitionQueued:'Queued', recognitionProcessing:'Recognizing…', recognitionReady:'Ready to review', recognitionError:'Recognition needs attention', overlapReasonMechanic:'Shared core play: {value}', overlapReasonOperation:'Same operation', overlapReasonGoal:'Same play goal', overlapReasonScene:'Same play setting', overlapReasonSkill:'Similar skills only', overlapReasonNone:'No meaningful overlap',
    allBrands:'All brands', allCategories:'All toy types', allSkills:'All skills', otherUnspecified:'Other / Unspecified',
    purchasePriority:'Purchase priority', overlaps:'Overlaps with these library toys', viewAll:'View all {count}', high:'High', medium:'Medium', low:'Low',
    exactDuplicate:'Exact duplicate', highSubstitution:'High substitution', mediumSubstitution:'Medium substitution', skillSimilarityOnly:'Similar skills only',
    noOverlap:'No meaningful substitute found. Shared skill labels alone do not count as duplication.',
    adminMode:'Admin mode', managerDashboard:'Manager dashboard', pendingCatalogReview:'Catalog items awaiting review', suspectedDuplicates:'Suspected duplicates', noPendingReview:'No items awaiting review.', noDuplicates:'No duplicate candidates.', backendDiagnostics:'Backend diagnostics', backendAvailable:'Backend available', backendUnavailable:'Backend unavailable', quotaUnavailable:'Quota unavailable', pendingSync:'Pending catalog deletions to sync: {count}', loading:'Loading…', signIn:'Sign in', signOut:'Exit manager mode', adminPassword:'Administrator password', brand:'Brand', englishName:'English name', chineseName:'Chinese name', aliases:'Aliases', mergeTarget:'Merge into canonical key', exportBackup:'Export backup', restoreBackup:'Restore backup',
    addedToLibrary:'Added to Toy Library', permanentDelete:'Permanently delete', confirmDelete:'Confirm permanent delete',
    adminPasswordRequired:'Enter the administrator password.', adminUnconfigured:'The administrator service is not configured.', adminIncorrectPassword:'Incorrect administrator password.', adminSignInFailed:'Administrator sign-in failed.', adminVerificationRequired:'Administrator verification is required.', adminOperationFailed:'Administrator operation failed.', catalogSyncFailed:'Catalog synchronization failed.', recognitionServiceUnconfigured:'The AI service is not configured.', recognitionFailed:'Image recognition failed.', recognitionNoResult:'Image recognition returned no result.', unsupportedBackup:'This backup file is not supported.',
    liked:'Love', neutral:'Okay', disliked:'Not interested', set:'Set', setParent:'Set parent', setChild:'Set child',
    onShelf:'On shelf', stored:'Stored', hidden:'Not in use / Hidden', generate:'Generate', noData:'Nothing here yet.',
    category:{uncategorized:'Uncategorized',cognitive:'Cognitive',blocks_construction:'Blocks / Construction',puzzles_matching:'Puzzles / Matching',fine_motor:'Fine motor',pretend_play:'Pretend play',sensory:'Sensory',music:'Music',vehicles_tracks:'Vehicles / Tracks',dolls_plush:'Dolls / Plush',books_cards:'Books / Cards',outdoor_gross_motor:'Outdoor / Gross motor',open_ended:'Open-ended materials',language_cognitive:'Language / Cognitive',arts_crafts:'Arts / Crafts',other:'Other'},
    skill:{logic:'Logic',math:'Early math',sorting:'Sorting',memory:'Memory',problem_solving:'Problem solving',cause_effect:'Cause & effect',spatial_awareness:'Spatial awareness',fine_motor:'Fine motor',hand_eye:'Hand-eye coordination',visual_spatial:'Visual-spatial',language:'Language',matching:'Matching',attention:'Attention',creativity:'Creativity',pretend_play:'Pretend play',social:'Social interaction',gross_motor:'Gross motor',sensory_exploration:'Sensory exploration',practical_life:'Practical life',colour:'Colour recognition',observation:'Observation',music:'Music',shapes:'Shape recognition',balance:'Balance control',rules:'Rule awareness',body_coordination:'Body coordination',grasping:'Grasping',aesthetics:'Aesthetic expression',visual_tracking:'Visual tracking',strategy:'Strategic thinking',social_cognition:'Social cognition',animal_cognition:'Animal knowledge',science:'Early science',open_play:'Open-ended play',imagination:'Imagination',letters:'Letter awareness',oral_motor:'Oral motor'},
  },
  zh: {
    home:'首页', library:'玩具库', rotation:'轮换', wishlist:'心愿单', settings:'设置', standardCatalog:'标准玩具库',
    addToy:'添加玩具', recognizeToy:'AI 图片识别', pendingReview:'待确认', confirmAdd:'确认入库', retryRecognition:'重新识别', remove:'移除', edit:'编辑', delete:'删除', save:'保存', cancel:'取消', close:'关闭', search:'搜索品牌 / 产品名称',
    name:'产品名称', skills:'能力', minimumAge:'建议起始月龄', maximumAge:'建议结束月龄', image:'图片', language:'语言', theme:'外观', system:'跟随系统', light:'浅色', dark:'深色', languageEnglish:'English', languageChinese:'中文', monthUnit:'月', removeToy:'从玩具库移除', confirmRemoveToy:'确定从玩具库移除此玩具吗？',
    recognitionQueued:'等待识别', recognitionProcessing:'AI 识别中…', recognitionReady:'等待确认', recognitionError:'识别需要处理', overlapReasonMechanic:'共同核心玩法：{value}', overlapReasonOperation:'操作方式相同', overlapReasonGoal:'游戏目标相同', overlapReasonScene:'使用场景相同', overlapReasonSkill:'仅能力相似', overlapReasonNone:'未发现明显重合',
    allBrands:'全部品牌', allCategories:'全部玩具类型', allSkills:'全部能力', otherUnspecified:'其他 / 未填写品牌',
    purchasePriority:'购买优先级', overlaps:'与家里这些玩具功能重合', viewAll:'查看全部 {count} 件', high:'高', medium:'中', low:'低',
    exactDuplicate:'完全重复', highSubstitution:'高度替代', mediumSubstitution:'中度替代', skillSimilarityOnly:'仅能力相似',
    noOverlap:'暂未发现明显替代品；共享能力标签本身不会判为重复。',
    adminMode:'管理员模式', managerDashboard:'管理员工作台', pendingCatalogReview:'待审核标准玩具', suspectedDuplicates:'疑似重复', noPendingReview:'暂无待审核条目。', noDuplicates:'暂无疑似重复。', backendDiagnostics:'后端诊断', backendAvailable:'后端可用', backendUnavailable:'后端不可用', quotaUnavailable:'配额信息不可用', pendingSync:'待同步的标准库删除：{count}', loading:'加载中…', signIn:'登录', signOut:'退出管理员模式', adminPassword:'管理员密码', brand:'品牌', englishName:'英文名称', chineseName:'中文名称', aliases:'别名', mergeTarget:'合并到 canonicalKey', exportBackup:'导出备份', restoreBackup:'恢复备份',
    addedToLibrary:'已加入玩具库', permanentDelete:'永久删除条目', confirmDelete:'确认永久删除',
    adminPasswordRequired:'请输入管理员密码。', adminUnconfigured:'管理员服务尚未配置。', adminIncorrectPassword:'管理员密码不正确。', adminSignInFailed:'管理员登录失败。', adminVerificationRequired:'需要管理员验证。', adminOperationFailed:'管理员操作失败。', catalogSyncFailed:'标准库同步失败。', recognitionServiceUnconfigured:'AI 服务尚未配置。', recognitionFailed:'图片识别失败。', recognitionNoResult:'图片识别没有返回结果。', unsupportedBackup:'不支持此备份文件。',
    liked:'很喜欢', neutral:'一般', disliked:'没兴趣', set:'套装', setParent:'套装父项', setChild:'套装子玩具',
    onShelf:'在架', stored:'收纳', hidden:'不再使用 / 隐藏', generate:'生成', noData:'暂无内容。',
    category:{uncategorized:'未分类',cognitive:'益智类玩具',blocks_construction:'积木/建构',puzzles_matching:'拼图/配对',fine_motor:'精细动作',pretend_play:'角色扮演',sensory:'感官探索',music:'音乐',vehicles_tracks:'车辆/轨道',dolls_plush:'娃娃/毛绒',books_cards:'阅读/卡片',outdoor_gross_motor:'户外/大运动',open_ended:'开放式材料',language_cognitive:'语言/认知',arts_crafts:'美术/手工',other:'其他'},
    skill:{logic:'逻辑推理',math:'数学启蒙',sorting:'分类能力',memory:'记忆力',problem_solving:'问题解决',cause_effect:'因果关系',spatial_awareness:'空间认知',fine_motor:'精细动作',hand_eye:'手眼协调',visual_spatial:'视觉空间',language:'语言',matching:'认知配对',attention:'专注力',creativity:'创造力',pretend_play:'角色扮演',social:'社交互动',gross_motor:'大运动',sensory_exploration:'感官探索',practical_life:'生活技能',colour:'颜色认知',observation:'观察力',music:'音乐',shapes:'形状认知',balance:'平衡控制',rules:'规则意识',body_coordination:'身体协调',grasping:'抓握能力',aesthetics:'审美表达',visual_tracking:'视觉追踪',strategy:'策略思维',social_cognition:'社会认知',animal_cognition:'动物认知',science:'科学启蒙',open_play:'开放式游戏',imagination:'想象力',letters:'字母启蒙',oral_motor:'口腔运动'}
  }
};
export function createI18n(store) {
  const language = () => store.state.settings.language === 'system' ? (navigator.language.startsWith('zh') ? 'zh' : 'en') : store.state.settings.language;
  const t = (key, params = {}) => {
    const parts = String(key).split('.'); let value = DICTIONARY[language()]; for (const part of parts) value = value?.[part];
    return String(value || key).replace(/\{(\w+)\}/g, (_, name) => params[name] ?? '');
  };
  return { t, get language() { return language(); }, setLanguage(value) { store.update(state => { state.settings.language = value; }, 'language'); } };
}
